name: "HITLT"
description: "Run the hardware-in-the-loop tests"

inputs:
  testcase:
    description: "pattern selecting the tests to be executed"
    required: true
    default: "none"

runs:
  using: "composite"
  steps:
    - name: "Check the Pmod UART interface to be available"
      shell: bash
      run: ls /dev/ttyPmodUSB0 > /dev/null
    - name: "Fix the interface to be used for testing"
      shell: bash
      run: echo "{ hitlt-serial-dev = \"/dev/ttyPmodUSB0\"; }" > build-config-local.nix
    - name: "Pull the Nix devShell from the cache"
      shell: bash
      run: nix build --no-link .#devShells.x86_64-linux.default
    - name: "Run synthesis, P&R, and the test(s)"
      shell: bash
      run: |
        nix develop \
          --command bash \
          -c "cabal run -- hitlt -p ${{ inputs.testcase }}"
