#!/bin/bash

mkdir -p /root/.ssh
echo -e "${2}" > /root/.ssh/${1} && chmod 600 /root/.ssh/${1}
echo -e "\
\nhost github.com-${1}\n\
  User git\n\
  Hostname github.com\n\
  IdentityFile /root/.ssh/${1}\n\
" >> /root/.ssh/config

if [ -f "flake.nix" ] && [ -f "flake.lock" ]; then
  sed -i "s!github.com/QBayLogic/${1}!github.com-${1}/QBayLogic/${1}!g" flake.lock flake.nix
fi
